# Generated by Django 5.2.6 on 2025-09-07 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ICD10', '0002_icdchapter_icdblock_icddisease_diseaseextrainfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='icddisease',
            name='code_no_sign',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='icddisease',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
