# Generated by Django 5.2.6 on 2025-09-07 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ICD10', '0003_icddisease_code_no_sign_icddisease_updated_at'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='diseaseextrainfo',
            table='disease_extra_info',
        ),
        migrations.AlterModelTable(
            name='icdblock',
            table='icd_block',
        ),
        migrations.AlterModelTable(
            name='icdchapter',
            table='icd_chapter',
        ),
        migrations.AlterModelTable(
            name='icddisease',
            table='icd_disease',
        ),
    ]
