# Generated by Django 5.2.6 on 2025-09-10 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ICD10', '0004_alter_diseaseextrainfo_table_alter_icdblock_table_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='address',
            new_name='hospital',
        ),
        migrations.RemoveField(
            model_name='user',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='user',
            name='updated_by',
        ),
        migrations.AddField(
            model_name='user',
            name='is_verified_doctor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='license_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_file',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.IntegerField(choices=[(1, 'GUEST'), (2, 'DOCTOR'), (3, 'ADMIN')], default=1),
        ),
    ]
