# Generated by Django 5.2.6 on 2025-09-16 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ICD10', '0006_user_email_verified_alter_user_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='icdblock',
            old_name='code_range',
            new_name='code',
        ),
    ]
