# Generated by Django 5.2.6 on 2025-10-08 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ICD10', '0007_rename_code_range_icdblock_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='icdblock',
            old_name='title',
            new_name='title_en',
        ),
        migrations.RenameField(
            model_name='icdchapter',
            old_name='title',
            new_name='title_en',
        ),
        migrations.RenameField(
            model_name='icddisease',
            old_name='title',
            new_name='title_en',
        ),
    ]
