# Generated by Django 5.2.6 on 2025-10-08 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ICD10', '0008_rename_title_icdblock_title_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='icdblock',
            name='title_vi',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='icdchapter',
            name='title_vi',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='icddisease',
            name='title_vi',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
