# Generated by Django 5.2.6 on 2025-10-13 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ICD10', '0010_chatsession_chatmessage_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='icdblock',
            options={'ordering': ['code']},
        ),
        migrations.AlterModelOptions(
            name='icdchapter',
            options={'ordering': ['code']},
        ),
        migrations.AlterModelOptions(
            name='icddisease',
            options={'ordering': ['code']},
        ),
        migrations.AddIndex(
            model_name='icdblock',
            index=models.Index(fields=['code'], name='icd_block_codeS_idx'),
        ),
        migrations.AddIndex(
            model_name='icdchapter',
            index=models.Index(fields=['code'], name='icd_chapter_codeS_idx'),
        ),
        migrations.AddIndex(
            model_name='icddisease',
            index=models.Index(fields=['code'], name='icd_disease_codeS_idx'),
        ),
    ]
