# Generated by Django 5.2.6 on 2025-10-16 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ICD10', '0011_alter_icdblock_options_alter_icdchapter_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['timestamp'], 'verbose_name': 'Tin nhắn', 'verbose_name_plural': 'Tin nhắn'},
        ),
        migrations.AlterModelOptions(
            name='chatsession',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Phiên chat', 'verbose_name_plural': 'Phiên chat'},
        ),
        migrations.AlterModelOptions(
            name='icdblock',
            options={'ordering': ['code'], 'verbose_name': 'Nhóm bệnh', 'verbose_name_plural': 'Nhóm bệnh'},
        ),
        migrations.AlterModelOptions(
            name='icdchapter',
            options={'ordering': ['code'], 'verbose_name': 'Chương', 'verbose_name_plural': 'Chương'},
        ),
        migrations.AlterModelOptions(
            name='icddisease',
            options={'ordering': ['code'], 'verbose_name': 'Bệnh', 'verbose_name_plural': 'Các bệnh'},
        ),
        migrations.AlterField(
            model_name='diseaseextrainfo',
            name='image_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
