# Generated by Django 5.2.6 on 2025-10-16 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ICD10', '0012_alter_chatmessage_options_alter_chatsession_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diseaseextrainfo',
            options={'verbose_name': 'Thông tin mở rộng về bệnh', 'verbose_name_plural': 'Thông tin mở rộng về bệnh'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Người dùng', 'verbose_name_plural': 'Người dùng'},
        ),
        migrations.RenameField(
            model_name='diseaseextrainfo',
            old_name='causes',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='diseaseextrainfo',
            name='treatment',
        ),
    ]
