# Generated by Django 5.2.6 on 2025-10-20 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ICD10', '0013_alter_diseaseextrainfo_options_alter_user_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='icddisease',
            name='description',
        ),
    ]
