# Generated by Django 5.2.6 on 2025-10-22 09:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ICD10', '0014_remove_icddisease_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback_Chatbot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Accepted'), (2, 'Rejected'), (3, 'Pending')], default=3)),
                ('chat_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='ICD10.chatmessage')),
                ('chat_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='ICD10.chatsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatbot_feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Phản hồi Chatbot',
                'verbose_name_plural': 'Phản hồi Chatbot',
                'db_table': 'icd_feedback_chatbot',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Feedback_ICD10',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=10, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('symptoms', models.TextField(blank=True, null=True)),
                ('image', models.TextField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Accepted'), (2, 'Rejected'), (3, 'Pending')], default=3)),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='ICD10.icddisease')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Phản hồi',
                'verbose_name_plural': 'Phản hồi',
                'db_table': 'icd_feedback',
                'ordering': ['-created_at'],
            },
        ),
    ]
