# Generated by Django 5.2.6 on 2025-10-22 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ICD10', '0015_feedback_chatbot_feedback_icd10'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback_chatbot',
            options={'ordering': ['-created_at'], 'verbose_name': 'Phản hồi về Chatbot', 'verbose_name_plural': 'Phản hồi về Chatbot'},
        ),
        migrations.AlterModelOptions(
            name='feedback_icd10',
            options={'ordering': ['-created_at'], 'verbose_name': 'Phản hồi về ICD-10', 'verbose_name_plural': 'Phản hồi về ICD-10'},
        ),
    ]
