# Generated by Django 5.2.6 on 2025-10-22 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ICD10', '0016_alter_feedback_chatbot_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback_chatbot',
            name='chat_session',
        ),
        migrations.RemoveField(
            model_name='feedback_icd10',
            name='code',
        ),
        migrations.RemoveField(
            model_name='feedback_icd10',
            name='title',
        ),
    ]
