# Generated by Django 5.2.6 on 2025-11-05 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ICD10', '0018_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
