# Generated by Django 5.2.6 on 2025-11-14 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ICD10', '0019_alter_notification_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='icdchapter',
            name='chapter',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
