# Generated by Django 5.2.6 on 2025-11-14 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ICD10', '0020_icdchapter_chapter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='icdchapter',
            options={'ordering': ['chapter'], 'verbose_name': 'Chương', 'verbose_name_plural': 'Chương'},
        ),
        migrations.RemoveIndex(
            model_name='icdchapter',
            name='icd_chapter_codeS_idx',
        ),
        migrations.AlterField(
            model_name='icdchapter',
            name='chapter',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AddIndex(
            model_name='icdchapter',
            index=models.Index(fields=['chapter'], name='icd_chapter_codeS_idx'),
        ),
    ]
