# Generated by Django 5.2.6 on 2025-11-17 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ICD10', '0021_alter_icdchapter_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback_icd10',
            name='description',
        ),
        migrations.RemoveField(
            model_name='feedback_icd10',
            name='image',
        ),
        migrations.RemoveField(
            model_name='feedback_icd10',
            name='symptoms',
        ),
        migrations.AddField(
            model_name='feedback_icd10',
            name='block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='ICD10.icdblock'),
        ),
        migrations.AddField(
            model_name='feedback_icd10',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='ICD10.icdchapter'),
        ),
        migrations.AddField(
            model_name='feedback_icd10',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='feedback_icd10',
            name='title_vi',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='feedback_icd10',
            name='disease',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='ICD10.icddisease'),
        ),
    ]
