# Generated by Django 5.2.6 on 2025-11-26 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ICD10', '0022_remove_feedback_icd10_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback_chatbot',
            name='user',
        ),
    ]
