# Generated by Django 5.2.6 on 2025-11-26 11:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ICD10', '0023_remove_feedback_chatbot_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback_Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=10, null=True)),
                ('title_vi', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Accepted'), (2, 'Rejected'), (3, 'Pending')], default=3)),
                ('type_feedback', models.PositiveSmallIntegerField(choices=[(1, 'Chapter'), (2, 'Block'), (3, 'Disease')], default=1)),
                ('reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='ICD10.icdblock')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Phản hồi về Nhóm ICD-10',
                'verbose_name_plural': 'Phản hồi về Nhóm ICD-10',
            },
        ),
        migrations.CreateModel(
            name='Feedback_Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=10, null=True)),
                ('title_vi', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Accepted'), (2, 'Rejected'), (3, 'Pending')], default=3)),
                ('type_feedback', models.PositiveSmallIntegerField(choices=[(1, 'Chapter'), (2, 'Block'), (3, 'Disease')], default=1)),
                ('reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='ICD10.icdchapter')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Phản hồi về Chương ICD-10',
                'verbose_name_plural': 'Phản hồi về Chương ICD-10',
            },
        ),
        migrations.CreateModel(
            name='Feedback_Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=10, null=True)),
                ('title_vi', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Accepted'), (2, 'Rejected'), (3, 'Pending')], default=3)),
                ('type_feedback', models.PositiveSmallIntegerField(choices=[(1, 'Chapter'), (2, 'Block'), (3, 'Disease')], default=1)),
                ('reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='ICD10.icddisease')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Phản hồi về Mã bệnh ICD-10',
                'verbose_name_plural': 'Phản hồi về Mã bệnh ICD-10',
            },
        ),
        migrations.DeleteModel(
            name='Feedback_ICD10',
        ),
    ]
