# Generated by Django 5.2.6 on 2025-11-26 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ICD10', '0024_feedback_block_feedback_chapter_feedback_disease_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback_block',
            options={'ordering': ['-created_at'], 'verbose_name': 'Phản hồi về Nhóm ICD-10', 'verbose_name_plural': 'Phản hồi về Nhóm ICD-10'},
        ),
        migrations.AlterModelOptions(
            name='feedback_chapter',
            options={'ordering': ['-created_at'], 'verbose_name': 'Phản hồi về Chương ICD-10', 'verbose_name_plural': 'Phản hồi về Chương ICD-10'},
        ),
        migrations.AlterModelOptions(
            name='feedback_disease',
            options={'ordering': ['-created_at'], 'verbose_name': 'Phản hồi về Mã bệnh ICD-10', 'verbose_name_plural': 'Phản hồi về Mã bệnh ICD-10'},
        ),
        migrations.AlterModelTable(
            name='feedback_block',
            table='icd_feedback_block',
        ),
        migrations.AlterModelTable(
            name='feedback_chapter',
            table='icd_feedback_chapter',
        ),
        migrations.AlterModelTable(
            name='feedback_disease',
            table='icd_feedback_disease',
        ),
    ]
