# Generated by Django 5.2.6 on 2025-11-26 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ICD10', '0026_alter_feedback_block_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback_block',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='block_feedbacks', to='ICD10.icdchapter'),
        ),
        migrations.AddField(
            model_name='feedback_disease',
            name='block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disease_feedbacks', to='ICD10.icdblock'),
        ),
    ]
