# Generated by Django 5.2.6 on 2025-11-27 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ICD10', '0027_feedback_block_chapter_feedback_disease_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback_disease',
            name='disease_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_disease_feedbacks', to='ICD10.icddisease'),
        ),
    ]
