# Generated by Django 5.2.6 on 2025-12-01 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ICD10', '0028_feedback_disease_disease_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='verification_file',
            field=models.URLField(blank=True, null=True),
        ),
    ]
