# Generated by Django 5.2.6 on 2025-12-09 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ICD10', '0030_user_pending_email_user_pending_email_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
