# Generated by Django 5.2.6 on 2025-12-12 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ICD10', '0031_alter_chatmessage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback_chatbot',
            name='admin_reply',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedback_chatbot',
            name='replied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('feedback', 'Feedback'), ('verify', 'Doctor Verification'), ('system', 'System'), ('admin_feedback_icd', 'Admin Feedback ICD'), ('admin_feedback_chatbot', 'Admin Feedback Chatbot'), ('admin_doctor', 'Admin Doctor Verification')], default='system', max_length=50),
        ),
    ]
