# Generated by Django 5.2.6 on 2025-12-14 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ICD10', '0032_feedback_chatbot_admin_reply_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='adk_session_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
