# Generated by Django 5.2.6 on 2025-12-17 08:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ICD10', '0033_chatsession_adk_session_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=10)),
                ('path', models.CharField(max_length=255)),
                ('status_code', models.IntegerField()),
                ('response_time_ms', models.FloatField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'api_request_log',
                'indexes': [models.Index(fields=['created_at'], name='api_request_created_0cd382_idx'), models.Index(fields=['status_code'], name='api_request_status__5b8a12_idx'), models.Index(fields=['path'], name='api_request_path_eabdc1_idx')],
            },
        ),
    ]
