# Generated by Django 5.2.6 on 2025-12-20 09:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ICD10', '0036_loginevent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apirequestlog',
            options={'verbose_name': 'Nhật ký yêu cầu API', 'verbose_name_plural': 'Nhật ký yêu cầu API'},
        ),
        migrations.AlterModelOptions(
            name='loginevent',
            options={'ordering': ['-created_at'], 'verbose_name': 'Sự kiện đăng nhập', 'verbose_name_plural': 'Sự kiện đăng nhập'},
        ),
        migrations.AlterModelOptions(
            name='tokenusage',
            options={'verbose_name': 'Token trong chatbot', 'verbose_name_plural': 'Token trong chatbot'},
        ),
        migrations.AddField(
            model_name='loginevent',
            name='identifier',
            field=models.CharField(blank=True, help_text='Email hoặc username dùng để login', max_length=255, null=True, verbose_name='Định danh đăng nhập'),
        ),
        migrations.AlterField(
            model_name='apirequestlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo'),
        ),
        migrations.AlterField(
            model_name='apirequestlog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Địa chỉ IP'),
        ),
        migrations.AlterField(
            model_name='apirequestlog',
            name='method',
            field=models.CharField(max_length=10, verbose_name='HTTP Method'),
        ),
        migrations.AlterField(
            model_name='apirequestlog',
            name='path',
            field=models.CharField(max_length=255, verbose_name='Đường dẫn'),
        ),
        migrations.AlterField(
            model_name='apirequestlog',
            name='response_time_ms',
            field=models.FloatField(verbose_name='Thời gian phản hồi (ms)'),
        ),
        migrations.AlterField(
            model_name='apirequestlog',
            name='status_code',
            field=models.IntegerField(verbose_name='HTTP Status Code'),
        ),
        migrations.AlterField(
            model_name='apirequestlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Người dùng'),
        ),
        migrations.AlterField(
            model_name='apirequestlog',
            name='user_agent',
            field=models.TextField(blank=True, null=True, verbose_name='User Agent'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='content',
            field=models.TextField(verbose_name='Nội dung'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='image',
            field=models.URLField(blank=True, null=True, verbose_name='Hình ảnh'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('bot', 'Chatbot'), ('admin', 'Admin')], max_length=10, verbose_name='Vai trò'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ICD10.chatsession', verbose_name='Phiên chat'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Thời gian'),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='adk_session_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ADK Session ID'),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo'),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='summary_count',
            field=models.IntegerField(default=0, verbose_name='Số lần tóm tắt'),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='title',
            field=models.CharField(default='Cuộc hội thoại mới', max_length=255, verbose_name='Tiêu đề'),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Thời gian cập nhật'),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng'),
        ),
        migrations.AlterField(
            model_name='feedback_block',
            name='block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='ICD10.icdblock', verbose_name='Nhóm bệnh'),
        ),
        migrations.AlterField(
            model_name='feedback_block',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='block_feedbacks', to='ICD10.icdchapter', verbose_name='Chương'),
        ),
        migrations.AlterField(
            model_name='feedback_block',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Mã bệnh ICD-10'),
        ),
        migrations.AlterField(
            model_name='feedback_block',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo phản hồi'),
        ),
        migrations.AlterField(
            model_name='feedback_block',
            name='reason',
            field=models.TextField(blank=True, null=True, verbose_name='Lý do gửi phản hồi'),
        ),
        migrations.AlterField(
            model_name='feedback_block',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Accepted'), (2, 'Rejected'), (3, 'Pending')], default=3, verbose_name='Trạng thái phản hồi'),
        ),
        migrations.AlterField(
            model_name='feedback_block',
            name='title_vi',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tên bệnh'),
        ),
        migrations.AlterField(
            model_name='feedback_block',
            name='type_feedback',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Chapter'), (2, 'Block'), (3, 'Disease')], default=1, verbose_name='Loại phản hồi'),
        ),
        migrations.AlterField(
            model_name='feedback_block',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='block_feedbacks', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng'),
        ),
        migrations.AlterField(
            model_name='feedback_chapter',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='ICD10.icdchapter', verbose_name='Chương'),
        ),
        migrations.AlterField(
            model_name='feedback_chapter',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Mã bệnh ICD-10'),
        ),
        migrations.AlterField(
            model_name='feedback_chapter',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo phản hồi'),
        ),
        migrations.AlterField(
            model_name='feedback_chapter',
            name='reason',
            field=models.TextField(blank=True, null=True, verbose_name='Lý do gửi phản hồi'),
        ),
        migrations.AlterField(
            model_name='feedback_chapter',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Accepted'), (2, 'Rejected'), (3, 'Pending')], default=3, verbose_name='Trạng thái phản hồi'),
        ),
        migrations.AlterField(
            model_name='feedback_chapter',
            name='title_vi',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tên bệnh'),
        ),
        migrations.AlterField(
            model_name='feedback_chapter',
            name='type_feedback',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Chapter'), (2, 'Block'), (3, 'Disease')], default=1, verbose_name='Loại phản hồi'),
        ),
        migrations.AlterField(
            model_name='feedback_chapter',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapter_feedbacks', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng'),
        ),
        migrations.AlterField(
            model_name='feedback_chatbot',
            name='admin_reply',
            field=models.TextField(blank=True, null=True, verbose_name='Phản hồi của quản trị viên'),
        ),
        migrations.AlterField(
            model_name='feedback_chatbot',
            name='chat_message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='ICD10.chatmessage', verbose_name='Tin nhắn chatbot'),
        ),
        migrations.AlterField(
            model_name='feedback_chatbot',
            name='comments',
            field=models.TextField(blank=True, null=True, verbose_name='Bình luận'),
        ),
        migrations.AlterField(
            model_name='feedback_chatbot',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo phản hồi'),
        ),
        migrations.AlterField(
            model_name='feedback_chatbot',
            name='rating',
            field=models.IntegerField(blank=True, null=True, verbose_name='Đánh giá'),
        ),
        migrations.AlterField(
            model_name='feedback_chatbot',
            name='replied_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ngày phản hồi'),
        ),
        migrations.AlterField(
            model_name='feedback_chatbot',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Accepted'), (2, 'Rejected'), (3, 'Pending')], default=3, verbose_name='Trạng thái phản hồi'),
        ),
        migrations.AlterField(
            model_name='feedback_disease',
            name='block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disease_feedbacks', to='ICD10.icdblock', verbose_name='Nhóm bệnh'),
        ),
        migrations.AlterField(
            model_name='feedback_disease',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Mã bệnh ICD-10'),
        ),
        migrations.AlterField(
            model_name='feedback_disease',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo phản hồi'),
        ),
        migrations.AlterField(
            model_name='feedback_disease',
            name='disease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='ICD10.icddisease', verbose_name='Mã bệnh'),
        ),
        migrations.AlterField(
            model_name='feedback_disease',
            name='disease_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_disease_feedbacks', to='ICD10.icddisease', verbose_name='Bệnh cha'),
        ),
        migrations.AlterField(
            model_name='feedback_disease',
            name='reason',
            field=models.TextField(blank=True, null=True, verbose_name='Lý do gửi phản hồi'),
        ),
        migrations.AlterField(
            model_name='feedback_disease',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Accepted'), (2, 'Rejected'), (3, 'Pending')], default=3, verbose_name='Trạng thái phản hồi'),
        ),
        migrations.AlterField(
            model_name='feedback_disease',
            name='title_vi',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tên bệnh'),
        ),
        migrations.AlterField(
            model_name='feedback_disease',
            name='type_feedback',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Chapter'), (2, 'Block'), (3, 'Disease')], default=1, verbose_name='Loại phản hồi'),
        ),
        migrations.AlterField(
            model_name='feedback_disease',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disease_feedbacks', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng'),
        ),
        migrations.AlterField(
            model_name='icdblock',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='ICD10.icdchapter', verbose_name='Chương'),
        ),
        migrations.AlterField(
            model_name='icdblock',
            name='code',
            field=models.CharField(max_length=20, unique=True, verbose_name='Mã nhóm'),
        ),
        migrations.AlterField(
            model_name='icdblock',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Mô tả'),
        ),
        migrations.AlterField(
            model_name='icdblock',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tiêu đề tiếng Anh'),
        ),
        migrations.AlterField(
            model_name='icdblock',
            name='title_vi',
            field=models.CharField(max_length=255, verbose_name='Tiêu đề'),
        ),
        migrations.AlterField(
            model_name='icdchapter',
            name='chapter',
            field=models.CharField(max_length=10, unique=True, verbose_name='Chương'),
        ),
        migrations.AlterField(
            model_name='icdchapter',
            name='code',
            field=models.CharField(max_length=10, unique=True, verbose_name='Mã chương'),
        ),
        migrations.AlterField(
            model_name='icdchapter',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Mô tả'),
        ),
        migrations.AlterField(
            model_name='icdchapter',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tiêu đề tiếng Anh'),
        ),
        migrations.AlterField(
            model_name='icdchapter',
            name='title_vi',
            field=models.CharField(max_length=255, verbose_name='Tiêu đề'),
        ),
        migrations.AlterField(
            model_name='icddisease',
            name='block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diseases', to='ICD10.icdblock', verbose_name='Nhóm bệnh'),
        ),
        migrations.AlterField(
            model_name='icddisease',
            name='code',
            field=models.CharField(max_length=10, unique=True, verbose_name='Mã bệnh'),
        ),
        migrations.AlterField(
            model_name='icddisease',
            name='code_no_sign',
            field=models.CharField(max_length=10, verbose_name='Mã bệnh không dấu'),
        ),
        migrations.AlterField(
            model_name='icddisease',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_diseases', to='ICD10.icddisease', verbose_name='Bệnh cha'),
        ),
        migrations.AlterField(
            model_name='icddisease',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tiêu đề tiếng Anh'),
        ),
        migrations.AlterField(
            model_name='icddisease',
            name='title_vi',
            field=models.CharField(max_length=255, verbose_name='Tiêu đề'),
        ),
        migrations.AlterField(
            model_name='icddisease',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ngày cập nhật'),
        ),
        migrations.AlterField(
            model_name='loginevent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo'),
        ),
        migrations.AlterField(
            model_name='loginevent',
            name='device',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Thiết bị'),
        ),
        migrations.AlterField(
            model_name='loginevent',
            name='ip_adress',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Địa chỉ IP'),
        ),
        migrations.AlterField(
            model_name='loginevent',
            name='status',
            field=models.CharField(choices=[('SUCCESS', 'Success'), ('FAILURE', 'Failure')], default='SUCCESS', max_length=20, verbose_name='Trạng thái đăng nhập'),
        ),
        migrations.AlterField(
            model_name='loginevent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_events', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng'),
        ),
        migrations.AlterField(
            model_name='loginevent',
            name='user_agent',
            field=models.TextField(blank=True, verbose_name='User Agent'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='Đã đọc'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(verbose_name='Nội dung thông báo'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('feedback', 'Feedback'), ('verify', 'Doctor Verification'), ('system', 'System'), ('admin_feedback_icd', 'Admin Feedback ICD'), ('admin_feedback_chatbot', 'Admin Feedback Chatbot'), ('admin_doctor', 'Admin Doctor Verification')], default='system', max_length=50, verbose_name='Loại thông báo'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Người nhận'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Tiêu đề'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='url',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Liên kết'),
        ),
        migrations.AlterField(
            model_name='tokenusage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo'),
        ),
        migrations.AlterField(
            model_name='tokenusage',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Ngày sử dụng'),
        ),
        migrations.AlterField(
            model_name='tokenusage',
            name='input_tokens',
            field=models.IntegerField(default=0, verbose_name='Số token đầu vào'),
        ),
        migrations.AlterField(
            model_name='tokenusage',
            name='model',
            field=models.CharField(max_length=100, verbose_name='Mô hình AI'),
        ),
        migrations.AlterField(
            model_name='tokenusage',
            name='output_tokens',
            field=models.IntegerField(default=0, verbose_name='Số token đầu ra'),
        ),
        migrations.AlterField(
            model_name='tokenusage',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_usages', to='ICD10.chatsession', verbose_name='Phiên chatbot'),
        ),
        migrations.AlterField(
            model_name='tokenusage',
            name='total_tokens',
            field=models.IntegerField(default=0, verbose_name='Tổng số token'),
        ),
        migrations.AlterField(
            model_name='tokenusage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_usages', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.URLField(blank=True, null=True, verbose_name='Ảnh đại diện'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False, verbose_name='Email đã được xác minh'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tên'),
        ),
        migrations.AlterField(
            model_name='user',
            name='hospital',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nơi công tác'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Quản trị viên'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, verbose_name='Siêu quản trị viên'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_verified_doctor',
            field=models.BooleanField(default=False, verbose_name='Đã xác minh là bác sĩ'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Lần đăng nhập cuối'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Họ'),
        ),
        migrations.AlterField(
            model_name='user',
            name='license_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Số giấy phép hành nghề'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, null=True, verbose_name='Mật khẩu'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.IntegerField(choices=[(1, 'GUEST'), (2, 'DOCTOR'), (3, 'ADMIN')], default=1, verbose_name='Vai trò'),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Active'), (2, 'Inactive'), (3, 'Waiting')], default=3, verbose_name='Trạng thái'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ngày cập nhật'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, verbose_name='Tên đăng nhập'),
        ),
        migrations.AlterField(
            model_name='user',
            name='verification_file',
            field=models.URLField(blank=True, null=True, verbose_name='File xác minh bác sĩ'),
        ),
    ]
