# Generated by Django 5.2.6 on 2025-12-24 08:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ICD10', '0037_alter_apirequestlog_options_alter_loginevent_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['created_at'], 'verbose_name': 'Tin nhắn', 'verbose_name_plural': 'Tin nhắn'},
        ),
        migrations.RemoveIndex(
            model_name='chatmessage',
            name='gemini_msg_session_time_idx',
        ),
        migrations.AlterField(
            model_name='feedback_block',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Chấp nhận'), (2, 'Từ chối'), (3, 'Chưa xử lý')], default=3, verbose_name='Trạng thái phản hồi'),
        ),
        migrations.AlterField(
            model_name='feedback_block',
            name='type_feedback',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Chương'), (2, 'Nhóm bệnh'), (3, 'Bệnh')], default=1, verbose_name='Loại phản hồi'),
        ),
        migrations.AlterField(
            model_name='feedback_chapter',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Chấp nhận'), (2, 'Từ chối'), (3, 'Chưa xử lý')], default=3, verbose_name='Trạng thái phản hồi'),
        ),
        migrations.AlterField(
            model_name='feedback_chapter',
            name='type_feedback',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Chương'), (2, 'Nhóm bệnh'), (3, 'Bệnh')], default=1, verbose_name='Loại phản hồi'),
        ),
        migrations.AlterField(
            model_name='feedback_chatbot',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Chấp nhận'), (2, 'Từ chối'), (3, 'Chưa xử lý')], default=3, verbose_name='Trạng thái phản hồi'),
        ),
        migrations.AlterField(
            model_name='feedback_disease',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Chấp nhận'), (2, 'Từ chối'), (3, 'Chưa xử lý')], default=3, verbose_name='Trạng thái phản hồi'),
        ),
        migrations.AlterField(
            model_name='feedback_disease',
            name='type_feedback',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Chương'), (2, 'Nhóm bệnh'), (3, 'Bệnh')], default=1, verbose_name='Loại phản hồi'),
        ),
        migrations.AlterField(
            model_name='loginevent',
            name='status',
            field=models.CharField(choices=[('SUCCESS', 'Thành công'), ('FAILURE', 'Thất bại')], default='SUCCESS', max_length=20, verbose_name='Trạng thái đăng nhập'),
        ),
        migrations.AlterField(
            model_name='loginevent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='login_events', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.IntegerField(choices=[(1, 'Người dùng'), (2, 'Bác sĩ'), (3, 'Quản trị viên')], default=1, verbose_name='Vai trò'),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Hoạt động'), (2, 'Khóa'), (3, 'Chưa kích hoạt')], default=3, verbose_name='Trạng thái'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['session', 'created_at'], name='gemini_msg_session_time_idx'),
        ),
    ]
